trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install robotframework
      pip install robotframework-seleniumlibrary
    displayName: 'Install Robot Framework & Dependencies'

  - script: |
      mkdir -p results
      chmod 777 results
    displayName: 'Prepare Results Folder'

  - script: |
      ls -la
      ls -la tests/
    displayName: 'Check Directory Structure'

  - script: |
      robot -d results $(System.DefaultWorkingDirectory)/tests/
    displayName: 'Run Robot Tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'results/log.html'
      artifact: 'TestLog'
      publishLocation: 'pipeline'
    displayName: 'Publish Robot Framework Log'
