trigger:
  - main  # Veya test branch'ını yaz

pool:
  vmImage: 'ubuntu-latest'  # Linux ortamında çalıştır

steps:
  - checkout: self  # GitHub reposunu al

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install robotframework
      pip install robotframework-seleniumlibrary
    displayName: 'Install Robot Framework & Dependencies'

  - script: |
      robot -d results tests/
    displayName: 'Run Robot Tests'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'results'
      artifact: 'TestResults'
      publishLocation: 'pipeline'

